# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ['--allow-multiple-documents', '--unsafe']
  - id: check-added-large-files
- repo: https://github.com/pecigonzalo/pre-commit-shfmt
  rev: v2.2.0
  hooks:
  # Requires `shfmt` to be installed in the system
  - id: shell-fmt
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
    # Permit non-root redirects when using 'sudo' in scripts
    # e.g. `sudo microk8s config > ~/.kube/config`
    # Use `| sudo tee <file> > /dev/null` to write as root
    args: ['-e', 'SC2024', '-e', 'SC2016']
- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
    args: ['-conf', 'pre-commit/yamlfmt.yaml']
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.2
  hooks:
  # Run the linter.
  - id: ruff-check
    types_or: [python, pyi]
    args: [--fix, --config, 'pre-commit/ruff.toml']
  # Run the formatter.
  - id: ruff-format
    types_or: [python, pyi]
    args: [--config, 'pre-commit/ruff.toml']
