# Container-independent dynamic configuration for Traefik
http:
  middlewares:
    auth:
      forwardAuth:
        address: "https://dtp-docker.tail899731.ts.net/auth/users/me"
        trustForwardHeader: true
        authRequestHeaders:
        - "Authorization"
        - "Cookie"
        authResponseHeaders:
        - "X-Auth-User-ID"
        - "X-Auth-Roles"
