# Container-independent dynamic configuration for Traefik
http:
  middlewares:
    auth:
      forwardAuth:
        address: "http://forward-auth:8000/user/me"
        trustForwardHeader: true
        authRequestHeaders:
        - "Authorization"
        authResponseHeaders:
        - "X-Auth-User-ID"
        - "X-Auth-Roles"
