# Container-independent dynamic configuration for Traefik
http:
  middlewares:
    # Basic authentication middleware using htpasswd file
    auth:
      forwardAuth:
        address: "http://forward-auth:8000/user/me"
        trustForwardHeader: true
        authRequestHeaders:
        - "Authorization"
        authResponseHeaders:
        - "X-Auth-User-ID"
